package com.kd.personalstake.domain;

import java.math.BigDecimal;
import java.util.Date;

public class EvCg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.STAKENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String stakeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.ER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String erId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.EC_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String ecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.TG_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String tgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.USER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.ALIAS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.CHARGENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String chargeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.ASSET_NO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String assetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.INST_ADDR
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String instAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.METER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String meterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.MODEL_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.PWSP_MODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String pwspMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.POWER
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.RATED_MIN_P
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal ratedMinP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.MAXOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal maxoutvolt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.MINOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal minoutvolt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.MAXOUTCURRENT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal maxoutcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.UUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private BigDecimal uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.CREATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.CREATORUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String creatoruuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.UPDATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private Date updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.UPDATERUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String updateruuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.STATUS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.STAKENAME
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String stakename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.ROUSERIALNUM
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private Integer rouserialnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.SHARED
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private Integer shared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.PROVINCE_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.CITY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.COUNTY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.STAKE_TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String stakeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ev_cg.OU_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    private String ouCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.STAKENO
     *
     * @return the value of ev_cg.STAKENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getStakeno() {
        return stakeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.STAKENO
     *
     * @param stakeno the value for ev_cg.STAKENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setStakeno(String stakeno) {
        this.stakeno = stakeno == null ? null : stakeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.ER_ID
     *
     * @return the value of ev_cg.ER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getErId() {
        return erId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.ER_ID
     *
     * @param erId the value for ev_cg.ER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setErId(String erId) {
        this.erId = erId == null ? null : erId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.EC_ID
     *
     * @return the value of ev_cg.EC_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getEcId() {
        return ecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.EC_ID
     *
     * @param ecId the value for ev_cg.EC_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setEcId(String ecId) {
        this.ecId = ecId == null ? null : ecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.TG_ID
     *
     * @return the value of ev_cg.TG_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getTgId() {
        return tgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.TG_ID
     *
     * @param tgId the value for ev_cg.TG_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setTgId(String tgId) {
        this.tgId = tgId == null ? null : tgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.USER_ID
     *
     * @return the value of ev_cg.USER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.USER_ID
     *
     * @param userId the value for ev_cg.USER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.ALIAS
     *
     * @return the value of ev_cg.ALIAS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.ALIAS
     *
     * @param alias the value for ev_cg.ALIAS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.CHARGENO
     *
     * @return the value of ev_cg.CHARGENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getChargeno() {
        return chargeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.CHARGENO
     *
     * @param chargeno the value for ev_cg.CHARGENO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setChargeno(String chargeno) {
        this.chargeno = chargeno == null ? null : chargeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.ASSET_NO
     *
     * @return the value of ev_cg.ASSET_NO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getAssetNo() {
        return assetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.ASSET_NO
     *
     * @param assetNo the value for ev_cg.ASSET_NO
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setAssetNo(String assetNo) {
        this.assetNo = assetNo == null ? null : assetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.INST_ADDR
     *
     * @return the value of ev_cg.INST_ADDR
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getInstAddr() {
        return instAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.INST_ADDR
     *
     * @param instAddr the value for ev_cg.INST_ADDR
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setInstAddr(String instAddr) {
        this.instAddr = instAddr == null ? null : instAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.METER_ID
     *
     * @return the value of ev_cg.METER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getMeterId() {
        return meterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.METER_ID
     *
     * @param meterId the value for ev_cg.METER_ID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setMeterId(String meterId) {
        this.meterId = meterId == null ? null : meterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.MODEL_CODE
     *
     * @return the value of ev_cg.MODEL_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.MODEL_CODE
     *
     * @param modelCode the value for ev_cg.MODEL_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode == null ? null : modelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.TYPE
     *
     * @return the value of ev_cg.TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.TYPE
     *
     * @param type the value for ev_cg.TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.PWSP_MODE
     *
     * @return the value of ev_cg.PWSP_MODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getPwspMode() {
        return pwspMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.PWSP_MODE
     *
     * @param pwspMode the value for ev_cg.PWSP_MODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setPwspMode(String pwspMode) {
        this.pwspMode = pwspMode == null ? null : pwspMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.POWER
     *
     * @return the value of ev_cg.POWER
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.POWER
     *
     * @param power the value for ev_cg.POWER
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setPower(BigDecimal power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.RATED_MIN_P
     *
     * @return the value of ev_cg.RATED_MIN_P
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getRatedMinP() {
        return ratedMinP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.RATED_MIN_P
     *
     * @param ratedMinP the value for ev_cg.RATED_MIN_P
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setRatedMinP(BigDecimal ratedMinP) {
        this.ratedMinP = ratedMinP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.MAXOUTVOLT
     *
     * @return the value of ev_cg.MAXOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getMaxoutvolt() {
        return maxoutvolt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.MAXOUTVOLT
     *
     * @param maxoutvolt the value for ev_cg.MAXOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setMaxoutvolt(BigDecimal maxoutvolt) {
        this.maxoutvolt = maxoutvolt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.MINOUTVOLT
     *
     * @return the value of ev_cg.MINOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getMinoutvolt() {
        return minoutvolt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.MINOUTVOLT
     *
     * @param minoutvolt the value for ev_cg.MINOUTVOLT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setMinoutvolt(BigDecimal minoutvolt) {
        this.minoutvolt = minoutvolt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.MAXOUTCURRENT
     *
     * @return the value of ev_cg.MAXOUTCURRENT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getMaxoutcurrent() {
        return maxoutcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.MAXOUTCURRENT
     *
     * @param maxoutcurrent the value for ev_cg.MAXOUTCURRENT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setMaxoutcurrent(BigDecimal maxoutcurrent) {
        this.maxoutcurrent = maxoutcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.UUID
     *
     * @return the value of ev_cg.UUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public BigDecimal getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.UUID
     *
     * @param uuid the value for ev_cg.UUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setUuid(BigDecimal uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.CREATEDAT
     *
     * @return the value of ev_cg.CREATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.CREATEDAT
     *
     * @param createdat the value for ev_cg.CREATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.CREATORUUID
     *
     * @return the value of ev_cg.CREATORUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getCreatoruuid() {
        return creatoruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.CREATORUUID
     *
     * @param creatoruuid the value for ev_cg.CREATORUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setCreatoruuid(String creatoruuid) {
        this.creatoruuid = creatoruuid == null ? null : creatoruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.UPDATEDAT
     *
     * @return the value of ev_cg.UPDATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.UPDATEDAT
     *
     * @param updatedat the value for ev_cg.UPDATEDAT
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.UPDATERUUID
     *
     * @return the value of ev_cg.UPDATERUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getUpdateruuid() {
        return updateruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.UPDATERUUID
     *
     * @param updateruuid the value for ev_cg.UPDATERUUID
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setUpdateruuid(String updateruuid) {
        this.updateruuid = updateruuid == null ? null : updateruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.STATUS
     *
     * @return the value of ev_cg.STATUS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.STATUS
     *
     * @param status the value for ev_cg.STATUS
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.STAKENAME
     *
     * @return the value of ev_cg.STAKENAME
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getStakename() {
        return stakename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.STAKENAME
     *
     * @param stakename the value for ev_cg.STAKENAME
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setStakename(String stakename) {
        this.stakename = stakename == null ? null : stakename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.ROUSERIALNUM
     *
     * @return the value of ev_cg.ROUSERIALNUM
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public Integer getRouserialnum() {
        return rouserialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.ROUSERIALNUM
     *
     * @param rouserialnum the value for ev_cg.ROUSERIALNUM
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setRouserialnum(Integer rouserialnum) {
        this.rouserialnum = rouserialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.SHARED
     *
     * @return the value of ev_cg.SHARED
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public Integer getShared() {
        return shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.SHARED
     *
     * @param shared the value for ev_cg.SHARED
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setShared(Integer shared) {
        this.shared = shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.PROVINCE_CODE
     *
     * @return the value of ev_cg.PROVINCE_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.PROVINCE_CODE
     *
     * @param provinceCode the value for ev_cg.PROVINCE_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.CITY_CODE
     *
     * @return the value of ev_cg.CITY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.CITY_CODE
     *
     * @param cityCode the value for ev_cg.CITY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.COUNTY_CODE
     *
     * @return the value of ev_cg.COUNTY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.COUNTY_CODE
     *
     * @param countyCode the value for ev_cg.COUNTY_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.STAKE_TYPE
     *
     * @return the value of ev_cg.STAKE_TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getStakeType() {
        return stakeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.STAKE_TYPE
     *
     * @param stakeType the value for ev_cg.STAKE_TYPE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setStakeType(String stakeType) {
        this.stakeType = stakeType == null ? null : stakeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ev_cg.OU_CODE
     *
     * @return the value of ev_cg.OU_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public String getOuCode() {
        return ouCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ev_cg.OU_CODE
     *
     * @param ouCode the value for ev_cg.OU_CODE
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    public void setOuCode(String ouCode) {
        this.ouCode = ouCode == null ? null : ouCode.trim();
    }
}