package com.kd.personalstake.mapper;

import com.kd.personalstake.domain.EvCg;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface EvCgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    int deleteByPrimaryKey(String stakeno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    int insert(EvCg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    int insertSelective(EvCg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    EvCg selectByPrimaryKey(String stakeno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    int updateByPrimaryKeySelective(EvCg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ev_cg
     *
     * @mbggenerated Mon Aug 13 17:37:27 CST 2018
     */
    int updateByPrimaryKey(EvCg record);
}